#!/usr/bin/env python
# encoding: utf-8
VOCABULARY_SIZE = 10000
BATCH_SIZE = 32
INPUT_DIM = VOCABULARY_SIZE + 2
EMBEDDING_DIM = 100
HIDDEN_DIM = 256
OUTPUT_DIM = 1
LEARNING_RATE = 1e-2
CURRENT_MODEL_NAME = 'nationalism'  # or nationalism
IS_TRAIN = True
